version: "3.5"
services:
  tor:
    image: peterdavehello/tor-socks-proxy
    networks:
      - tarinetwork
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - "$PWD/config/tor/torrc:/etc/tor/torrc"
      - "$PWD/data/tor:/var/lib/tor"
  tari:
    image: tari_base_node:latest
    networks:
      - tarinetwork
    depends_on:
      - tor
    working_dir: /root/.tari
    volumes:
      - "$PWD/data/tari:/root/.tari"
  wait:
    image: waisbrot/wait
    networks:
      - tarinetwork
    environment:
      - TARGETS=tor:9050

networks:
  tarinetwork:
    name: tarinetwork
